spring:
  datasource:
    url: jdbc:mysql://13.125.249.52:3306/weekly?useSSL=false
    #url: jdbc:mysql://127.0.0.1:3306/weekly?useSSL=false
    password: root
    #password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    spring.datasource.filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mvc:
    view:
      prefix:
      suffix: .jsp
  cache:
    ehcache:
      config: ehcache.xml

server:
  port: 8080
mybatis:
  configuration:
    map-underscore-to-camel-case: true



