spring:
  datasource:
    url: jdbc:mysql://13.125.249.52:3306/weekly?useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix:
      suffix: .jsp
server:
  port: 8080
mybatis:
  configuration:
    map-underscore-to-camel-case: true


