spring:
  datasource:
    url: jdbc:mysql://13.125.249.52:3306/weekly
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix:
      suffix: .jsp
server:
  port: 8080

